#!/bin/bash

# Install PHP and required extensions
sudo apt-get update
sudo apt-get install -y php7.3 php7.3-bcmath php7.3-ctype php7.3-fileinfo php7.3-json php7.3-mbstring php7.3-opcache php7.3-pdo php7.3-tokenizer php7.3-xml php7.3-pgsql

# Install PostgreSQL
sudo apt-get install -y postgresql postgresql-contrib

# Install Apache or NGINX
sudo apt-get install -y apache2

# Install NodeJS v16
curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
sudo apt-get install -y nodejs

# Install PHP Composer
sudo apt-get install -y curl unzip
curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer
